name: Download Data

on:
  push:
    branches: ['main']
  workflow_dispatch:
  schedule:
    - cron: 59 23 * * *

jobs:
  download:
    runs-on: ubuntu-latest
    
    steps:
      - name: Setup temp folders
        run: mkdir -p ${{ runner.temp }}/main ${{ runner.temp }}/gh-pages ${{ runner.temp }}/json/days

      - name: Clone main branch
        working-directory: ${{ runner.temp }}/main
        run: git clone -b main --single-branch https://github.com/${{ github.repository }}

      - name: Clone gh-pages branch
        working-directory: ${{ runner.temp }}/gh-pages
        run: git clone -b gh-pages --single-branch https://github.com/${{ github.repository }}

      - uses: actions/setup-node@v4
        with:
          node-version: '22.x'

      - name: Clone previous days data
        working-directory: ${{ runner.temp }}/gh-pages/nodejs-download-stats-viewer
        run: "cp -r json/days/* ${{ runner.temp }}/json/days ||:"

      - name: Install dependencies
        working-directory: ${{ runner.temp }}/main/nodejs-download-stats-viewer
        run: npm ci

      - name: Download data
        working-directory: ${{ runner.temp }}/main/nodejs-download-stats-viewer
        run: dayDataFolder=${{ runner.temp }}/json/days dayListFolder=${{ runner.temp }}/json node index.js

      - name: Delete old data
        working-directory: ${{ runner.temp }}/gh-pages/nodejs-download-stats-viewer
        run: rm -rf json/days

      - name: Clone new days data
        working-directory: ${{ runner.temp }}/gh-pages/nodejs-download-stats-viewer
        run: cp -r ${{ runner.temp }}/json/days json

      - name: Clone new days list
        working-directory: ${{ runner.temp }}/gh-pages/nodejs-download-stats-viewer
        run: cp ${{ runner.temp }}/json/data.json .

      - name: Commit results
        uses: actions-js/push@v1.5
        with:
          directory: ${{ runner.temp }}/gh-pages/nodejs-download-stats-viewer
          empty: true
          message: 'added new day data'
          branch: 'gh-pages'
          github_token: ${{ secrets.GH_TOKEN }}
      